### ISSUE TITLE
Нужно добавить товару поле "Артикул". 

### ISSUE THREAD

**Issue by AlecCross** [feya-bilyzna/backend#17]
Сделать возможным в админке вносить,  изменять или удалять артикул товара.

Так как основными признаками конкретного товара будет являться Бредн и Артикул, нужно сейчас добавить артикул на стороне сервера. 

Обговорили что поле Название пока не убераем. Чтобы не сломать текущий фронтенд.

**Comment by lifearoundfreaks** [comment]
"удалять артикул товара" - что имелось в виду? необходимо разрешать оставлять это поле пустым?
